version: "3.9"

services:
  mongo:
    image: mongo
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./whishper_data/db_data:/data/db
      - ./whishper_data/db_data/logs/:/var/log/mongodb/
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER:-whishper}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS:-whishper}
    expose:
      - 27017
    command: ['--logpath', '/var/log/mongodb/mongod.log']

    
  # translate:
  #   container_name: whisper-libretranslate
  #   image: libretranslate/libretranslate:latest-cuda
  #   restart: unless-stopped
  #   volumes:
  #     - ./whishper_data/libretranslate/data:/home/libretranslate/.local/share
  #     - ./whishper_data/libretranslate/cache:/home/libretranslate/.local/cache
  #   env_file:
  #     - .env
  #   user: root
  #   tty: true
  #   environment:
  #     LT_DISABLE_WEB_UI: True
  #     LT_LOAD_ONLY: ${LT_LOAD_ONLY:-en,fr}
  #     LT_UPDATE_MODELS: True
  #   expose:
  #     - 5000
  #   networks:
  #     default:
  #       aliases:
  #         - translate
  #   deploy:
  #    resources:
  #      reservations:
  #        devices:
  #        - driver: nvidia
  #          count: all
  #          capabilities: [gpu]


  translate:
    container_name: whisper-libretranslate
    image: libretranslate/libretranslate:latest
    restart: unless-stopped
    volumes:
      - ./whishper_data/libretranslate/data:/home/libretranslate/.local/share
      - ./whishper_data/libretranslate/cache:/home/libretranslate/.local/cache
    env_file:
      - .env
    tty: true
    environment:
      LT_DISABLE_WEB_UI: True
      LT_UPDATE_MODELS: True
#      LT_DEBUG: True
    expose:
      - 5000
    networks:
      default:
        aliases:
          - translate
    healthcheck:
      test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']
      interval: 30s
      timeout: 5s
      retries: 5

  whishper:
    build: .
    env_file:
      - .env
    volumes:
      - ./whishper_data/uploads:/app/uploads
      - ./whishper_data/logs:/var/log/whishper
      - ./whishper_data/torch_models:/root/.cache/torch/
      - ./whishper_data/whisper_models:/app/models
    container_name: whishper
    restart: unless-stopped
    networks:
      default:
        aliases:
          - whishper
    ports:
      - 127.0.0.1:8082:80
    depends_on:
      - mongo
#      - translate
    environment:
      PUBLIC_INTERNAL_API_HOST: "http://127.0.0.1:80"
      PUBLIC_TRANSLATION_API_HOST: ""
      PUBLIC_API_HOST: ${WHISHPER_HOST:-}
      PUBLIC_WHISHPER_PROFILE: gpu
      WHISPER_MODELS_DIR: /app/models
      UPLOAD_DIR: /app/uploads
#    deploy:
#      resources:
#        reservations:
#          devices:
#          - driver: nvidia
#            count: all
#            capabilities: [gpu]
      CPU_THREADS: 4
